Firstname=Sudireddy
Lastname=AshokSai
DateofBirth=1999-08-15
Street=Reddybanda Street
Postalcode=522415
City=Guntur
State=Andhra Pradesh
Country=India
Phone=6301622508
Email=ashoksaisudireddy15@gmail.com
Password=AshSai@4582

