Firstname=Sudireddy
Lastname=AshokSai
DateofBirth=1998-08-19
Street=Kondamodu
Postalcode=522415
City=Guntur
State=Andhra Pradesh
Country=India
Phone=9645872156
Email=ash@gmail.com
Password=AshSai@2542

